### ISSUE TITLE
AES/GCM/NoPadding encryption in JAVA & decryption in JavaScript

### ISSUE THREAD

**Issue by kashif-sk** [java-crypto/cross_platform_crypto#3]
@java-crypto Thanks for this awesome repo.

I am using AES/GCM/NoPadding 128 bit. I want to encrypt in Java & decrypt it in Javascript.
I have tried some solution which didn't work. Unfortunately it didn't work.

Can you please help me out with this issue : https://stackoverflow.com/q/74917947/17166044

**Comment by MichaelsPlayground** [comment]
As your problem is not an issue with my code I'm closing this issue.
Original comment from me in your SO question: 
_The Java encryption code isn't returning the IV/nonce used for encryption so it is not part of the splitting in decryption code. Serious security warning: Do NOT use the above code in production as it is UNSECURE. You should consider to change your production code as the encryption in AES GCM mode gets total insecure when using a nonce more than one time with the same key (the Java code is using a static IV/nonce with 8 0x's)._

**Comment by kashif-sk** [comment]
@MichaelsPlayground 
Got it. Thanks a lot.
